<b>array operations<b>

In [7]:
import numpy as np

In [8]:
a=np.array([5,6,9])

In [9]:
a[0]

5

In [10]:
a[1]

6

In [11]:
a = np.array([[1,2],[3,4],[5,6]])

In [12]:
a.ndim

2

In [13]:
a=np.array([5,6,9])

In [14]:
a.ndim

1

In [15]:
a = np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [16]:
a.itemsize

8

In [17]:
a.dtype

dtype('int64')

In [18]:
a = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)

In [19]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [20]:
a.itemsize

8

In [21]:
a.size

6

In [22]:
a.shape

(3, 2)

In [23]:
a.dtype

dtype('float64')

In [24]:
a = np.array([[1,2],[3,4],[5,6]], dtype=complex)

In [25]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
l=range(5)

In [29]:
l

range(0, 5)

In [30]:
l[0]

0

In [31]:
l[4]

4

In [32]:
np.arange(1,5)

array([1, 2, 3, 4])

In [33]:
np.arange(1,5,2)

array([1, 3])

In [34]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [35]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [36]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [37]:
a.shape

(3, 2)

In [55]:
a = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)

In [56]:
a.reshape(2,3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [57]:
a.reshape(6,1)

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [58]:
a.ravel()

array([1., 2., 3., 4., 5., 6.])

In [60]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [61]:
a.max()

6.0

In [62]:
a.min()

1.0

In [63]:
a.sum()

21.0

In [64]:
a.sum(axis=0) 
# this will sum the rows

array([ 9., 12.])

In [65]:
a.sum(axis=1)
# this will sum the columns

array([ 3.,  7., 11.])

In [66]:
a.sqrt()

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [67]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [68]:
np.std(a)

1.707825127659933

In [69]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [70]:
a.ravel()

array([1, 2, 3, 4])

In [71]:
a.flatten()

array([1, 2, 3, 4])

In [72]:
a

array([[1, 2],
       [3, 4]])

In [73]:
b

array([[5, 6],
       [7, 8]])

In [74]:
a+b

array([[ 6,  8],
       [10, 12]])

In [75]:
a*b

array([[ 5, 12],
       [21, 32]])

In [76]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [77]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [78]:
a3 = np.array([

               [[1, 2, 3],

                [4, 5, 6],

                [7, 8, 9],

                [20, 21, 22]],

               [[10, 12, 13],

                [14, 15, 16],

                [17, 18, 19],

                [7, 8, 9]]

               ])

In [79]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [20, 21, 22]],

       [[10, 12, 13],
        [14, 15, 16],
        [17, 18, 19],
        [ 7,  8,  9]]])

In [80]:
a3.ndim

3

In [81]:
a3.shape

(2, 4, 3)

In [82]:
a3.sum(axis=0)

array([[11, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [27, 29, 31]])

In [83]:
a3.sum(axis=1)

array([[32, 36, 40],
       [48, 53, 57]])

In [85]:
a4 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [86]:
a4.ndim

3

In [87]:
a4.shape

(2, 2, 2)

In [88]:
a4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [89]:
a4.sum(axis=0)

array([[ 6,  8],
       [10, 12]])

In [90]:
a4.sum(axis=1)

array([[ 4,  6],
       [12, 14]])

In [91]:
n=[6,7,8]

In [93]:
n[0:2]

[6, 7]

In [94]:
n[-1]

8

In [95]:
a=np.array([6,7,8])

In [96]:
a[0:2]

array([6, 7])

In [97]:
a[-1]

8

In [100]:
a=np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [101]:
a[1,2]

3

In [102]:
a[0:2,2]

array([8, 3])

In [103]:
a[-1]

array([9, 3, 2])

In [104]:
a[-1,0:2]

array([9, 3])

In [105]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [106]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [ ]:
# iterate through array

In [108]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [109]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [113]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)

In [111]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [114]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [116]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [117]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [118]:
a=np.arange(30).reshape(2,15)

In [119]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [122]:
result=np.hsplit(a,3)

In [123]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [124]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [125]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [126]:
result=np.vsplit(a,2)

In [127]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [128]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [129]:
a=np.arange(12).reshape(3,4)

In [130]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
b=a>4

In [132]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [133]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [134]:
a[b]=-1

In [135]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [137]:
a=np.arange(12).reshape(3,4)

In [138]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [139]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [140]:
for cell in a:
    print(cell)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [142]:
for row in a:
    
#     print(row)
    for cell in a:
    print(cell)

IndentationError: expected an indented block (1386130838.py, line 4)

In [143]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [144]:
for x in np.nditer(a,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [145]:
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [146]:
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [147]:
for x in np.nditer(a,op_flags=['readwrite']):
  x[...]=x*x

In [148]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [149]:
b=np.arange(3,15,4).reshape(3,1)

In [150]:
b

array([[ 3],
       [ 7],
       [11]])

In [153]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


In [154]:
b=np.arange(3,19,5).reshape(4,1)

In [155]:
b

array([[ 3],
       [ 8],
       [13],
       [18]])

In [156]:
for x,y in np.nditer([a,b]):
    print(x,y)
#     not broadcastable

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 