In [30]:
###predict home prices using multivariate linear regression 
in python (using sklearn linear_model). Home prices are dependent on 
3 independent variables: area, bedrooms and age. Pandas 
dataframe is used to fill missing values first and then use 
that dataset to train a multivariate regression model.


In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [31]:
df= pd.read_csv("/Users/rmn7591/Documents/Repositories/coder/homePrices_township/home_prices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [32]:
###this function has been used to get the median of bedrooms
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [33]:
### using fillna i have filled all the NAN values with its median
df.bedrooms= df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [34]:
reg= linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [35]:
#y=m1x1+m2x2+m3x3+b
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [36]:
reg.intercept_

383724.9999999998

In [40]:
reg.predict([[3000,3,40]])

array([444400.])

In [41]:
137.25*3000+-26025.*3+40* -6825.

60675.0

In [42]:
reg.predict([[2500,4,5]])

array([588625.])